# Generated by Django 4.1.3 on 2022-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('del_date', models.DateField()),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
